### ISSUE TITLE
Improved auto mode frequency selection

### ISSUE THREAD

**Issue by DrArcularis** [fallenangel42/electron#19]
I have been experimenting with using auto mode with a fairly tight carrier frequency range (max - min < 100 Hz) to randomly get low frequency separations with strong triphase effect. However, when the left and right carrier frequencies are exactly equal, the result can either cancel out, or add together to be very strong. I recommend rounding frequencies to a finer grid (0.1 Hz or 0.2 Hz) and selecting another frequency if the two chosen frequencies are exactly equal.

**Comment by fallenangel42** [comment]
I'm sorry it took me such a long time to get back to you @DrArcularis . Do you think you might be able to send a pull request with this change? It sounds intriguing!

**Comment by DrArcularis** [comment]
Yes, I've been busy here too, but I just coded up a change and submitted a pull request. Let me know if you'd like to discuss further.

**Comment by fallenangel42** [comment]
Fixed by PR #20
