### ISSUE TITLE
Settings Logger

### ISSUE THREAD

**Issue by DrArcularis** [fallenangel42/electron#2]
Add feature to remember all settings changes that have been applied in a session, and save them in a human-readable format (e.g. CSV file) for future reference. These files would be useful to help novice drivers learn effective settings. These files could also form the basis for "playlists".

**Comment by Vyladence** [comment]
I think it would be most useful to be able to save settings per channel so you could save left/right presets separately. It would just make the system more versatile in my opinion. This also works so if you have something in the left you want copied to the right, you can just save the settings you like and load them into the correct channel.

**Comment by merlot-vin** [comment]
I think that, until we need the bandwidth, json might be the preferable external file format for paramters.  Then stringify can be used to take them in and out of javascript objects.

**Comment by DrArcularis** [comment]
> I think it would be most useful to be able to save settings per channel so you could save left/right presets separately. It would just make the system more versatile in my opinion. This also works so if you have something in the left you want copied to the right, you can just save the settings you like and load them into the correct channel.

**Comment by DrArcularis** [comment]
@Vyladence I was thinking of the logger as a timestamped recording of entire session, and in that case I'd want to keep left and right together in the same file, like a stereo recording of an audio file. If you think of the logger as the ability snapshot just one particular set of parameters (a "preset"), then I agree that saving left/right separately would be useful. Perhaps we should add both timestamped recording and presets, eventually...

**Comment by DrArcularis** [comment]
@merlot-vin I agree that bandwidth will not be an issue with these files. One nice thing about csv files is they are easy to work with outside of Javascript (in Excel or Google Sheets, for example) and might be easier for new drivers in the community to learn from. But whoever works on this upgrade can choose whatever they think is best. Note that if the first row (line) of the csv file contains column headings it is more or less self-documenting, but I see no issue with including a version id column or any other useful information.

A related issue I've been thinking about is timestamps. Would it make more sense to have absolute timestamps from the day the session was originally recorded, or offset timestamps from the start of that session?

**Comment by merlot-vin** [comment]
I would timestamp at start of session. It would more easily map to a view that one might capture for/in Audacity or similar.
